services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1oncomandaproj
      POSTGRES_DB: on_comanda
    ports:
      - '5432:5432'

  api:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://postgres:1oncomandaproj@db:5432/on_comanda"
    depends_on:
      - db